"""
Configuration for Phase 11 Clinical-Style Report Generator & PDF Generation.

Defines output directories, configurable research risk thresholds, styling parameters,
and required medical/research disclaimers.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional


def get_default_reports_dir() -> Path:
    """Return default output directory for generated reports."""
    return Path(__file__).resolve().parent / "outputs" / "reports"


@dataclass
class ReportConfig:
    """
    Configuration settings for clinical-style multimodal assessment report generation.
    """
    # Output Directory Paths
    output_dir: str = field(default_factory=lambda: str(get_default_reports_dir()))
    pdf_subdir: str = "pdf"
    json_subdir: str = "json"
    summary_csv_subdir: str = "summary"

    # Research Risk Category Thresholds (Configurable)
    # Applied to predicted probability p in [0, 1]
    low_risk_threshold: float = 0.35
    moderate_risk_threshold: float = 0.65

    # Confidence Score Thresholds (from Phase 9: confidence in [0, 100]%)
    high_confidence_threshold: float = 80.0
    moderate_confidence_threshold: float = 60.0

    # System & Institution Branding
    institution_name: str = "AI Multimodal Retinal Research Consortium"
    system_title: str = "AI-Based Multimodal Retinal & Clinical Analysis System"
    report_title: str = "Multimodal Retinal & Clinical Assessment Report"
    document_version: str = "v1.0.0 (Research Edition)"

    # PDF Layout and Styling
    page_size: str = "A4"  # 'A4' or 'LETTER'
    primary_color: str = "#1A365D"    # Deep Navy
    secondary_color: str = "#2B6CB0"  # Clinical Blue
    accent_color: str = "#D69E2E"     # Amber/Gold
    alert_color: str = "#C53030"      # Crimson
    success_color: str = "#2F855A"    # Forest Green
    neutral_dark: str = "#2D3748"     # Charcoal Text
    neutral_light: str = "#F7FAFC"    # Soft Grey Background
    table_header_bg: str = "#EDF2F7"

    # Mandatory Safety & Research Disclaimer
    disclaimer: str = (
        "IMPORTANT RESEARCH NOTICE: This report is generated by an experimental multimodal artificial "
        "intelligence research prototype for investigational and decision-support purposes only. "
        "The predictions, probability estimates, uncertainty metrics, and explainability visualizations "
        "do not constitute a clinically verified medical diagnosis and must never substitute for "
        "professional evaluation, diagnosis, or treatment by a board-certified healthcare provider."
    )

    def get_output_path(self) -> Path:
        p = Path(self.output_dir).resolve()
        p.mkdir(parents=True, exist_ok=True)
        return p

    def get_pdf_dir(self) -> Path:
        p = self.get_output_path() / self.pdf_subdir
        p.mkdir(parents=True, exist_ok=True)
        return p

    def get_json_dir(self) -> Path:
        p = self.get_output_path() / self.json_subdir
        p.mkdir(parents=True, exist_ok=True)
        return p

    def get_summary_csv_dir(self) -> Path:
        p = self.get_output_path() / self.summary_csv_subdir
        p.mkdir(parents=True, exist_ok=True)
        return p


def get_default_report_config() -> ReportConfig:
    """Return default ReportConfig instance."""
    return ReportConfig()
